const PROJECTS = {
  LOAD_PROJECTS: "LOAD_PROJECTS",
  PROJECTS_LOADED_SUCCESS: "PROJECTS_LOADED_SUCCESS",
  PROJECTS_LOADED_FAIL: "PROJECTS_LOADED_FAIL",
};

const STATS = {
  LOAD_STATS: "LOAD_STATS",
  STATS_LOAD_SUCCESS: "STATS_LOAD_SUCCES",
  STATS_LOAD_FAIL: "STATS_LOAD_FAIL",
};

export { PROJECTS, STATS };
