const PROJECTS = {
  LOAD_PROJECTS: "LOAD_PROJECTS",
  PROJECTS_LOADED_SUCCESS: "PROJECTS_LOADED_SUCCESS",
  PROJECTS_LOADED_FAIL: "PROJECTS_LOADED_FAIL",

  LOAD_ONE_PROJECT: "LOAD_ONE_PROJECT",
  PROJECT_ONE_LOADED_SUCCESS: "PROJECT_ONE_LOADED_SUCCESS",
  PROJECT_ONE_LOADED_FAIL: "PROJECT_ONE_LOADED_FAIL",

  ADD_PROJECT: "ADD_PROJECT",
  PROJECT_ADDED_SUCCESS: "PROJECT_ADDED_SUCCESS",
  PROJECT_ADDED_FAIL: "PROJECT_ADDED_FAIL",
};

//not used
const STATS = {
  LOAD_STATS: "LOAD_STATS",
  STATS_LOAD_SUCCESS: "STATS_LOAD_SUCCES",
  STATS_LOAD_FAIL: "STATS_LOAD_FAIL",
};

export { PROJECTS, STATS };
